### ISSUE TITLE
In Window, copy and paste OTP code (number only) do not work when CapsLock is on

### ISSUE THREAD

**Issue by rednguyen** [k2peter/ngx-otp-input#11]
**Describe the bug**
In Window, copy and paste OTP code (number only) do not work when CapsLock is on.

**To Reproduce**

1. Make sure you are using Window
2. Go to : "https://ngx-otp-input.vercel.app/" on any browser
3. Turn on CapsLock
4. Copy: 1234
5. Ctrl-V to paste to the input field
-> Code can't be pasted

**Expected behavior**
Code should be pasted even CapsLock is on.

**Comment by sathishpsy89** [comment]
Hi @rednguyen 

In pattern.directive.ts under hostlistener keydown event, we need to replace **e.key** to **e.key.toLowerCase( )**

@HostListener('keydown', ['$event']) onKeyDown(e: KeyboardEvent): void {
    if (
      this.allowedKeys.includes(e.key) ||
      (**e.key.toLowerCase( )** === 'a' && e.ctrlKey === true) || // Allow: Ctrl+A
      (**e.key.toLowerCase( )** === 'c' && e.ctrlKey === true) || // Allow: Ctrl+C
      (**e.key.toLowerCase( )** === 'v' && e.ctrlKey === true) || // Allow: Ctrl+V
      (**e.key.toLowerCase( )** === 'x' && e.ctrlKey === true) || // Allow: Ctrl+X
      (**e.key.toLowerCase( )** === 'a' && e.metaKey === true) || // Cmd+A (Mac)
      (**e.key.toLowerCase( )** === 'c' && e.metaKey === true) || // Cmd+C (Mac)
      (**e.key.toLowerCase( )** === 'v' && e.metaKey === true) || // Cmd+V (Mac)
      (**[ngx-otp-input-master.zip](https://github.com/k2peter/ngx-otp-input/files/8997307/ngx-otp-input-master.zip)** === 'x' && e.metaKey === true) // Cmd+X (Mac)
    ) {
      return; // let it happen, don't do anything
    } else if (!this.pattern.test(e.key)) {
      e.preventDefault();
    }
  }

**Comment by sathishpsy89** [comment]
Hi @rednguyen 

  In **pattern.directive.ts** file, under **@Hostlistener (keydown)** event we need to replace **e.key** to **e.key.toLowerCase( )**, whereas this issue got resolved.

**Path to that file :**  **"ngx-otp-input-master\projects\ngx-otp-input\src\lib\pattern.directive.ts"**

import { Directive, HostListener, Input } from '@angular/core';

@Directive({
  selector: '[ngxOtpPattern]',
})
export class PatternDirective {
  // allowed keys apart from numeric characters
  private allowedKeys = [
    'Backspace',
    'ArrowLeft',
    'ArrowRight',
    'Escape',
    'Tab',
  ];

  @Input('ngxOtpPattern') pattern: RegExp;

  @HostListener('keydown', ['$event']) onKeyDown(e: KeyboardEvent): void {
    if (
      this.allowedKeys.includes(e.key) ||
      (**e.key.toLowerCase( )** === 'a' && e.ctrlKey === true) || // Allow: Ctrl+A
      (**e.key.toLowerCase( )** === 'c' && e.ctrlKey === true) || // Allow: Ctrl+C
      (**e.key.toLowerCase( )** === 'v' && e.ctrlKey === true) || // Allow: Ctrl+V
      (**e.key.toLowerCase( )** === 'x' && e.ctrlKey === true) || // Allow: Ctrl+X
      (**e.key.toLowerCase( )** === 'a' && e.metaKey === true) || // Cmd+A (Mac)
      (**e.key.toLowerCase( )** === 'c' && e.metaKey === true) || // Cmd+C (Mac)
      (**e.key.toLowerCase( )** === 'v' && e.metaKey === true) || // Cmd+V (Mac)
      (**e.key.toLowerCase( )** === 'x' && e.metaKey === true) // Cmd+X (Mac)
    ) {
      return; // let it happen, don't do anything
    } else if (!this.pattern.test(e.key)) {
      e.preventDefault();
    }
  }
}

[ngx-otp-input-master.zip](https://github.com/k2peter/ngx-otp-input/files/8997330/ngx-otp-input-master.zip)

**Comment by k2peter** [comment]
I pushed a new version (v0.11.1) which includes the fix now! Thanks for your effort.

**Comment by k2peter** [comment]
My bad, I didn't update the Stackblitz version. It should work now. Could you confirm it please?
